version: '3'
services:
  mysql:
    image: ${MYSQL_IMAGE:-mysql:5.7}
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_DATABASE=dev_ssm
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    # MariaDB >= 10.0.12 doesn't enable Performance Schema by default so we need to do it manually
    # https://mariadb.com/kb/en/mariadb/performance-schema-overview/#activating-the-performance-schema
    command: --performance-schema --secure-file-priv=""
    volumes:
    # /tmp volume is required for "SELECT * INTO OUTFILE" used in tests
      - /tmp/:/tmp/:rw
