# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

# Require `revel` command (compiled later from vendor dir)
required = ["github.com/revel/cmd/revel"]
[[override]]
  name = "github.com/revel/cmd"
  version = "^0.14.2"
  source = "github.com/percona-lab/revel-cmd"

# Override version for transitive dependencies
# otherwise we fetch the latest.
[[override]]
  name = "github.com/revel/config"
  version = "^0.14.0"
[[override]]
  name = "github.com/revel/modules"
  version = "^0.14.0"
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "github.com/fsnotify/fsnotify"
[[override]]
  name = "github.com/cactus/go-statsd-client"
  version = "=v3.1.1"
[[override]]
  name = "github.com/percona/go-mysql"
  revision = "8863d30f944bc83d6d7b1d5c4b3cfa2d69d84cf3"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "^0.8.0"

[[constraint]]
  name = "github.com/revel/revel"
  version = "^0.14.0"

[[constraint]]
  name = "github.com/youtube/vitess"
  revision = "98f9189aa016e2a3afafa9ff42cde55bde421d3c"

# PMM-2569: Version 1.4.0 introduces support for new auth methods in MySQL 8.
#           At the moment of writing it's not required for this project as it uses older MySQL version.
[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "^1.4.0"

[prune]
  go-tests = true

[[override]]
  name = "github.com/shatteredsilicon/ssm"
  revision = "7a9f3c5b23e3f498dbe597cdaca95f6c5d7bdf05"